export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const SET_VIEW_PRODUCT_ID = "SET_VIEW_PRODUCT_ID";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const DISPLAY_CART_PRODUCT = "DISPLAY_CART_PRODUCT";
